import streamlit as st

st.set_page_config(page_title="Draft Review", layout="wide")
st.title("Draft Review")

st.subheader("Current Draft")
st.write("**Title:** New Smartphone Launch")
st.write("**Content:** Dummy text generated by Drafter.")
st.write("**Tags:** #Smartphone #Launch")
st.write("**Critic Status:** ⚠️ 'revolutionary' detected.")
st.write("**Revision Count:** 1")

st.divider()
st.subheader("Human-in-the-Loop Decision")
col1, col2, col3 = st.columns(3)

if 'action' not in st.session_state:
    st.session_state.action = None

with col1:
    if st.button("Approve", use_container_width=True):
        st.session_state.action = "approve"
with col2:
    if st.button("Reject", use_container_width=True):
        st.session_state.action = "reject"
with col3:
    if st.button("Edit", use_container_width=True):
        st.session_state.action = "edit"

if st.session_state.action == "approve":
    st.success("Draft Approved.")

elif st.session_state.action == "reject":
    feedback = st.text_area("Rejection Feedback:")
    if st.button("Send to Reviser"):
        st.warning("Sending feedback to Reviser...")

elif st.session_state.action == "edit":
    edited_content = st.text_area("Edit Content:", value="Dummy text generated by Drafter.")
    if st.button("Save and Publish"):
        st.info("Saving edited content...")